### ISSUE TITLE
GTM and GTAG datalayers does not work anymore

### ISSUE THREAD

**Issue by huang-julien** [GoogleChromeLabs/third-party-capital#55]
the latest TPC doesn't work anymore due to the datalayers object. GTM does not add the push function into the datalayers arrays.

expected:

![image](https://github.com/user-attachments/assets/207aafbf-2c93-4c82-9152-3c989c312476)

received: 
![image](https://github.com/user-attachments/assets/05685b3c-06f5-41e5-a68a-d535bcbdb256)

**Comment by flashdesignory** [comment]
@huang-julien - we can probably close this one, right?

**Comment by huang-julien** [comment]
yup indeed :D
